### PR TITLE
detection of nutriscore labels

### PR DESCRIPTION
**Pull request by llucifer97**
added a functionality for detection of nutriscore from images of food products

### CODE REVIEW

**Comment by teolemon** [comment]
Thank you so much @llucifer97 :-)
@offvince can you have a look ?

**Comment by tanmaypandey7** [comment]
Hi, @teolemon , from what I found [this is the nutriscore detection](https://github.com/llucifer97/nutriscore_tensorflow/blob/master/nutriscore-detection/nutriscore_detection.ipynb) which is being talked about. But it doesn't detect the labels (A, B, C, D, E). Can I improve it to detect all 5 labels, or is this implementation okay?

**Comment by teolemon** [comment]
That would be awesome :-)

**Comment by raphael0202** [comment]
A nutriscore detection model has been deployed in Robotoff

**Pull request closed without merging**
