### PR TITLE
added ingredients extraction model and fixed hastags

### PR DESCRIPTION
**Pull request by tanmaypandey7**
updated the channel hashtags from #computervision #machinelearning to #ai-computervision #ai-machinelearning

### CODE REVIEW

**Comment by tanmaypandey7** [comment]
added the ingredients extraction model in the repo

**Comment by raphael0202** [comment]
Hi @tanmaypandey7, can you give some context about what this model does?

**Comment by tanmaypandey7** [comment]
Hi @raphael0202, this model automatically crops the ingredients list from the food packets. In reference to issue 
https://github.com/openfoodfacts/openfoodfacts-ai/issues/40

**Comment by CloCkWeRX** [comment]
This seems promising, is there much detail on accuracy, false positives, etc? Is there anything that can be done to further train the model?

**Comment by tanmaypandey7** [comment]
@CloCkWeRX I would say 50% accuracy, I don't have idea about false positives. Yes, there is huge room for improvement. I use a simple CNN trained on about 50 or 60 images and which I am further using it to test on the images.
One idea I didn't implement due to lack of knowledge was -> 
 simple object detection ->  text detection-> text recognition -> more-specific object detection

**Pull request closed without merging**
