### PR TITLE
Added rotation correction

### PR DESCRIPTION
**Pull request by ashishkumar1550**
Class for image processing, currently added feature for rotation correction, more are to be added ( like deblurring )

### CODE REVIEW

**Comment by teolemon** [comment]
@ashishkumar1550 Can I create you a separate repository ?

**Comment by ashishkumar1550** [comment]
@teolemon  sure.. thanks

**Comment by teolemon** [comment]
swell. I've giving you rights to that repo

**Comment by teolemon** [comment]
https://github.com/openfoodfacts/off-image-processing

**Comment by CloCkWeRX** [comment]
Is it worth closing this PR, and committing to the new repo?

**Comment by ashishkumar1550** [comment]
hi @CloCkWeRX Sorry, I am no longer active here.

**Pull request closed without merging**
