### PR TITLE
Added a link for annotated barcode dataset 

### PR DESCRIPTION
**Pull request by iamvibhorsingh**
The dataset is comprised of 185 images in total with 161 images for training and 24 for testing. All images are annotated and annotations are present in the files train_labels.csv and test_labels.csv.

### CODE REVIEW

**Comment by teolemon** [comment]
@visin Can I create you a separate repository ?

**Comment by visin** [comment]
Yup, no problem.

**Comment by teolemon** [comment]
@visin sorry for the delay. Could you create a separate repo ? I'd like to make it an official off repo.
`openfoodfacts-ai-annotated-barcodes` ?

**Comment by CloCkWeRX** [comment]
If you create it, I'll populate the dataset into it @teolemon

**Comment by iamvibhorsingh** [comment]
@teolemon Sorry for such a long delay. I've been off github for a while, I have made the repo as you requested. It can be found [here.](https://github.com/iamvibhorsingh/openfoodfacts-ai-annotated-barcodes). 
Again, I apologize for the long delay.

**Pull request closed without merging**
